"""Alert management and notification system."""

from __future__ import annotations
import smtplib
import json
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
from datetime import datetime, timedelta
from typing import Any
from dataclasses import dataclass
from enum import Enum
import requests

from loguru import logger

from .metrics import Alert, AlertSeverity


class NotificationChannel(Enum):
    """Available notification channels."""
    EMAIL = "email"
    WEBHOOK = "webhook"
    SLACK = "slack"
    DISCORD = "discord"
    CONSOLE = "console"


@dataclass
class NotificationConfig:
    """Configuration for notification channels."""
    channel: NotificationChannel
    enabled: bool = True
    config: dict[str, Any] = None
    
    def __post_init__(self):
        if self.config is None:
            self.config = {}


class EmailNotifier:
    """Email notification handler."""
    
    def __init__(self, config: dict[str, Any]):
        self.smtp_server = config.get("smtp_server", "localhost")
        self.smtp_port = config.get("smtp_port", 587)
        self.username = config.get("username", "")
        self.password = config.get("password", "")
        self.from_email = config.get("from_email", "")
        self.to_emails = config.get("to_emails", [])
        self.use_tls = config.get("use_tls", True)
    
    def send_alert(self, alert: Alert) -> bool:
        """Send email alert."""
        try:
            msg = MimeMultipart()
            msg['From'] = self.from_email
            msg['To'] = ", ".join(self.to_emails)
            msg['Subject'] = f"[Asmblr Alert] {alert.name} - {alert.severity.value.upper()}"
            
            body = self._format_email_body(alert)
            msg.attach(MimeText(body, 'html'))
            
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            if self.use_tls:
                server.starttls()
            
            if self.username and self.password:
                server.login(self.username, self.password)
            
            server.send_message(msg)
            server.quit()
            
            logger.info(f"Email alert sent for {alert.name}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email alert: {e}")
            return False
    
    def _format_email_body(self, alert: Alert) -> str:
        """Format email body."""
        severity_colors = {
            AlertSeverity.INFO: "#17a2b8",
            AlertSeverity.WARNING: "#ffc107", 
            AlertSeverity.ERROR: "#dc3545",
            AlertSeverity.CRITICAL: "#6f42c1"
        }
        
        color = severity_colors.get(alert.severity, "#6c757d")
        
        return f"""
        <html>
        <body>
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                <div style="background-color: {color}; color: white; padding: 20px; border-radius: 5px 5px 0 0;">
                    <h2 style="margin: 0;">🚨 Asmblr Alert</h2>
                    <p style="margin: 5px 0 0 0;">{alert.severity.value.upper()} - {alert.name}</p>
                </div>
                
                <div style="background-color: #f8f9fa; padding: 20px; border: 1px solid #dee2e6; border-top: none;">
                    <h3>Alert Details</h3>
                    <p><strong>Message:</strong> {alert.message}</p>
                    <p><strong>Condition:</strong> {alert.condition}</p>
                    <p><strong>Threshold:</strong> {alert.threshold}</p>
                    <p><strong>Trigger Count:</strong> {alert.trigger_count}</p>
                    <p><strong>Last Triggered:</strong> {alert.last_triggered.strftime('%Y-%m-%d %H:%M:%S') if alert.last_triggered else 'Never'}</p>
                </div>
                
                <div style="background-color: #e9ecef; padding: 15px; border: 1px solid #dee2e6; border-top: none; border-radius: 0 0 5px 5px;">
                    <p style="margin: 0; font-size: 12px; color: #6c757d;">
                        This alert was generated by Asmblr MVP Generator at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.
                    </p>
                </div>
            </div>
        </body>
        </html>
        """


class WebhookNotifier:
    """Webhook notification handler."""
    
    def __init__(self, config: dict[str, Any]):
        self.url = config.get("url", "")
        self.headers = config.get("headers", {})
        self.timeout = config.get("timeout", 30)
        self.retry_count = config.get("retry_count", 3)
    
    def send_alert(self, alert: Alert) -> bool:
        """Send webhook alert."""
        try:
            payload = {
                "alert_name": alert.name,
                "severity": alert.severity.value,
                "message": alert.message,
                "condition": alert.condition,
                "threshold": alert.threshold,
                "trigger_count": alert.trigger_count,
                "last_triggered": alert.last_triggered.isoformat() if alert.last_triggered else None,
                "timestamp": datetime.now().isoformat(),
                "source": "asmblr"
            }
            
            for attempt in range(self.retry_count):
                try:
                    response = requests.post(
                        self.url,
                        json=payload,
                        headers=self.headers,
                        timeout=self.timeout
                    )
                    response.raise_for_status()
                    
                    logger.info(f"Webhook alert sent for {alert.name}")
                    return True
                    
                except requests.RequestException as e:
                    if attempt == self.retry_count - 1:
                        raise
                    logger.warning(f"Webhook attempt {attempt + 1} failed: {e}")
                    time.sleep(2 ** attempt)  # Exponential backoff
            
        except Exception as e:
            logger.error(f"Failed to send webhook alert: {e}")
            return False


class SlackNotifier:
    """Slack notification handler."""
    
    def __init__(self, config: dict[str, Any]):
        self.webhook_url = config.get("webhook_url", "")
        self.channel = config.get("channel", "#alerts")
        self.username = config.get("username", "Asmblr Bot")
        self.icon_emoji = config.get("icon_emoji", ":robot_face:")
    
    def send_alert(self, alert: Alert) -> bool:
        """Send Slack alert."""
        try:
            severity_colors = {
                AlertSeverity.INFO: "#17a2b8",
                AlertSeverity.WARNING: "#ffc107",
                AlertSeverity.ERROR: "#dc3545", 
                AlertSeverity.CRITICAL: "#6f42c1"
            }
            
            color = severity_colors.get(alert.severity, "#6c757d")
            emoji = {"INFO": "ℹ️", "WARNING": "⚠️", "ERROR": "❌", "CRITICAL": "🚨"}.get(alert.severity.value, "📢")
            
            payload = {
                "channel": self.channel,
                "username": self.username,
                "icon_emoji": self.icon_emoji,
                "attachments": [
                    {
                        "color": color,
                        "title": f"{emoji} Asmblr Alert: {alert.name}",
                        "fields": [
                            {
                                "title": "Severity",
                                "value": alert.severity.value.upper(),
                                "short": True
                            },
                            {
                                "title": "Trigger Count",
                                "value": str(alert.trigger_count),
                                "short": True
                            },
                            {
                                "title": "Message",
                                "value": alert.message,
                                "short": False
                            },
                            {
                                "title": "Condition",
                                "value": alert.condition,
                                "short": True
                            },
                            {
                                "title": "Threshold",
                                "value": str(alert.threshold),
                                "short": True
                            }
                        ],
                        "footer": "Asmblr MVP Generator",
                        "ts": int(datetime.now().timestamp())
                    }
                ]
            }
            
            response = requests.post(self.webhook_url, json=payload, timeout=30)
            response.raise_for_status()
            
            logger.info(f"Slack alert sent for {alert.name}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send Slack alert: {e}")
            return False


class DiscordNotifier:
    """Discord notification handler."""
    
    def __init__(self, config: dict[str, Any]):
        self.webhook_url = config.get("webhook_url", "")
        self.username = config.get("username", "Asmblr Bot")
        self.avatar_url = config.get("avatar_url", "")
    
    def send_alert(self, alert: Alert) -> bool:
        """Send Discord alert."""
        try:
            severity_colors = {
                AlertSeverity.INFO: 0x17a2b8,
                AlertSeverity.WARNING: 0xffc107,
                AlertSeverity.ERROR: 0xdc3545,
                AlertSeverity.CRITICAL: 0x6f42c1
            }
            
            color = severity_colors.get(alert.severity, 0x6c757d)
            emoji = {"INFO": "ℹ️", "WARNING": "⚠️", "ERROR": "❌", "CRITICAL": "🚨"}.get(alert.severity.value, "📢")
            
            payload = {
                "username": self.username,
                "avatar_url": self.avatar_url,
                "embeds": [
                    {
                        "title": f"{emoji} Asmblr Alert: {alert.name}",
                        "description": alert.message,
                        "color": color,
                        "fields": [
                            {
                                "name": "Severity",
                                "value": alert.severity.value.upper(),
                                "inline": True
                            },
                            {
                                "name": "Trigger Count",
                                "value": str(alert.trigger_count),
                                "inline": True
                            },
                            {
                                "name": "Condition",
                                "value": alert.condition,
                                "inline": True
                            },
                            {
                                "name": "Threshold",
                                "value": str(alert.threshold),
                                "inline": True
                            }
                        ],
                        "footer": {
                            "text": "Asmblr MVP Generator"
                        },
                        "timestamp": datetime.now().isoformat()
                    }
                ]
            }
            
            response = requests.post(self.webhook_url, json=payload, timeout=30)
            response.raise_for_status()
            
            logger.info(f"Discord alert sent for {alert.name}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send Discord alert: {e}")
            return False


class ConsoleNotifier:
    """Console notification handler."""
    
    def send_alert(self, alert: Alert) -> bool:
        """Send console alert."""
        try:
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            severity_symbol = {
                AlertSeverity.INFO: "ℹ️",
                AlertSeverity.WARNING: "⚠️",
                AlertSeverity.ERROR: "❌",
                AlertSeverity.CRITICAL: "🚨"
            }.get(alert.severity, "📢")
            
            logger.info(f"\n{severity_symbol} [{timestamp}] ALERT: {alert.name}")
            logger.info(f"   Severity: {alert.severity.value.upper()}")
            logger.info(f"   Message: {alert.message}")
            logger.info(f"   Condition: {alert.condition}")
            logger.info(f"   Threshold: {alert.threshold}")
            logger.info(f"   Trigger Count: {alert.trigger_count}")
            if alert.last_triggered:
                logger.info(f"   Last Triggered: {alert.last_triggered.strftime('%Y-%m-%d %H:%M:%S')}")
            print()
            
            logger.info(f"Console alert displayed for {alert.name}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to display console alert: {e}")
            return False


class AlertNotificationManager:
    """Manages alert notifications across multiple channels."""
    
    def __init__(self):
        self.notifiers: dict[NotificationChannel, Any] = {}
        self.notification_configs: dict[NotificationChannel, NotificationConfig] = {}
        self.rate_limits: dict[str, datetime] = {}
        self.min_interval = timedelta(minutes=5)  # Minimum time between same alert notifications
    
    def add_notification_channel(self, config: NotificationConfig) -> bool:
        """Add a notification channel."""
        try:
            if config.channel == NotificationChannel.EMAIL:
                notifier = EmailNotifier(config.config)
            elif config.channel == NotificationChannel.WEBHOOK:
                notifier = WebhookNotifier(config.config)
            elif config.channel == NotificationChannel.SLACK:
                notifier = SlackNotifier(config.config)
            elif config.channel == NotificationChannel.DISCORD:
                notifier = DiscordNotifier(config.config)
            elif config.channel == NotificationChannel.CONSOLE:
                notifier = ConsoleNotifier()
            else:
                logger.error(f"Unsupported notification channel: {config.channel}")
                return False
            
            self.notifiers[config.channel] = notifier
            self.notification_configs[config.channel] = config
            
            logger.info(f"Added notification channel: {config.channel.value}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to add notification channel {config.channel}: {e}")
            return False
    
    def remove_notification_channel(self, channel: NotificationChannel) -> None:
        """Remove a notification channel."""
        if channel in self.notifiers:
            del self.notifiers[channel]
        if channel in self.notification_configs:
            del self.notification_configs[channel]
        logger.info(f"Removed notification channel: {channel.value}")
    
    def send_alert(self, alert: Alert) -> dict[NotificationChannel, bool]:
        """Send alert through all enabled channels."""
        results = {}
        
        # Check rate limiting
        now = datetime.now()
        if alert.name in self.rate_limits:
            if now - self.rate_limits[alert.name] < self.min_interval:
                logger.debug(f"Alert {alert.name} rate limited")
                return results
        
        for channel, config in self.notification_configs.items():
            if not config.enabled:
                continue
            
            try:
                notifier = self.notifiers.get(channel)
                if notifier:
                    success = notifier.send_alert(alert)
                    results[channel] = success
                    
                    if success:
                        logger.info(f"Alert {alert.name} sent via {channel.value}")
                    else:
                        logger.error(f"Failed to send alert {alert.name} via {channel.value}")
                        
            except Exception as e:
                logger.error(f"Error sending alert {alert.name} via {channel.value}: {e}")
                results[channel] = False
        
        # Update rate limit
        self.rate_limits[alert.name] = now
        
        return results
    
    def test_notifications(self) -> dict[NotificationChannel, bool]:
        """Test all notification channels."""
        from .metrics import Alert, AlertSeverity
        
        test_alert = Alert(
            name="test_notification",
            severity=AlertSeverity.INFO,
            condition="test = true",
            threshold=1.0,
            message="This is a test notification from Asmblr"
        )
        
        return self.send_alert(test_alert)
    
    def get_channel_status(self) -> dict[str, Any]:
        """Get status of all notification channels."""
        status = {}
        
        for channel, config in self.notification_configs.items():
            status[channel.value] = {
                "enabled": config.enabled,
                "configured": channel in self.notifiers,
                "config": {k: v for k, v in config.config.items() if k not in ["password", "token"]}
            }
        
        return status


# Global notification manager instance
_global_notification_manager = AlertNotificationManager()


def get_notification_manager() -> AlertNotificationManager:
    """Get the global notification manager instance."""
    return _global_notification_manager


def setup_default_notifications() -> None:
    """Setup default notification channels from environment variables."""
    import os
    
    # Console notifications (always enabled)
    console_config = NotificationConfig(
        channel=NotificationChannel.CONSOLE,
        enabled=True
    )
    _global_notification_manager.add_notification_channel(console_config)
    
    # Email notifications
    if os.getenv("ALERT_EMAIL_ENABLED", "false").lower() == "true":
        email_config = NotificationConfig(
            channel=NotificationChannel.EMAIL,
            enabled=True,
            config={
                "smtp_server": os.getenv("ALERT_SMTP_SERVER", "localhost"),
                "smtp_port": int(os.getenv("ALERT_SMTP_PORT", "587")),
                "username": os.getenv("ALERT_EMAIL_USERNAME", ""),
                "password": os.getenv("ALERT_EMAIL_PASSWORD", ""),
                "from_email": os.getenv("ALERT_EMAIL_FROM", ""),
                "to_emails": os.getenv("ALERT_EMAIL_TO", "").split(","),
                "use_tls": os.getenv("ALERT_EMAIL_USE_TLS", "true").lower() == "true"
            }
        )
        _global_notification_manager.add_notification_channel(email_config)
    
    # Webhook notifications
    if os.getenv("ALERT_WEBHOOK_ENABLED", "false").lower() == "true":
        webhook_config = NotificationConfig(
            channel=NotificationChannel.WEBHOOK,
            enabled=True,
            config={
                "url": os.getenv("ALERT_WEBHOOK_URL", ""),
                "headers": json.loads(os.getenv("ALERT_WEBHOOK_HEADERS", "{}")),
                "timeout": int(os.getenv("ALERT_WEBHOOK_TIMEOUT", "30")),
                "retry_count": int(os.getenv("ALERT_WEBHOOK_RETRY_COUNT", "3"))
            }
        )
        _global_notification_manager.add_notification_channel(webhook_config)
    
    # Slack notifications
    if os.getenv("ALERT_SLACK_ENABLED", "false").lower() == "true":
        slack_config = NotificationConfig(
            channel=NotificationChannel.SLACK,
            enabled=True,
            config={
                "webhook_url": os.getenv("ALERT_SLACK_WEBHOOK_URL", ""),
                "channel": os.getenv("ALERT_SLACK_CHANNEL", "#alerts"),
                "username": os.getenv("ALERT_SLACK_USERNAME", "Asmblr Bot"),
                "icon_emoji": os.getenv("ALERT_SLACK_ICON_EMOJI", ":robot_face:")
            }
        )
        _global_notification_manager.add_notification_channel(slack_config)
    
    # Discord notifications
    if os.getenv("ALERT_DISCORD_ENABLED", "false").lower() == "true":
        discord_config = NotificationConfig(
            channel=NotificationChannel.DISCORD,
            enabled=True,
            config={
                "webhook_url": os.getenv("ALERT_DISCORD_WEBHOOK_URL", ""),
                "username": os.getenv("ALERT_DISCORD_USERNAME", "Asmblr Bot"),
                "avatar_url": os.getenv("ALERT_DISCORD_AVATAR_URL", "")
            }
        )
        _global_notification_manager.add_notification_channel(discord_config)
